server:
  port: 92
spring:
  application:
    name: springcloud-config-92

  #github仓库地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lishuai13/springcloud-config.git  #github仓库地址
